//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeRunner.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61697637962276641366442297247367117738114719863473648131982449728688116728695866572989524473392982963976411147683588415878214189996163533584547175794158118148724298832798898333399786561459152644144669959887341481968319172987357989785791366732849932788343772112176614723858474959919713855398876956427631354172668133549845585632211935573662181331613137869866693259374322169811683635325321597242889358147123358117774914653787371368574784376721652181792371635288376729784967526824915192526744935187989571347746222113 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62	1649	1731	76	51	1295	349	719	52	1984	2015	2171	981	1809	181	1715
        ///161	99	1506	1658	84	78	533	242	1685	86	107	1548	670	960	1641	610
        ///95	2420	2404	2293	542	2107	2198	121	109	209	2759	1373	1446	905	1837	111
        ///552	186	751	527	696	164	114	530	558	307	252	200	481	142	205	479
        ///581	1344	994	1413	120	112	656	1315	1249	193	1411	1280	110	103	74	1007
        ///2536	5252	159	179	4701	1264	1400	2313	4237	161	142	4336	1061	3987	2268	4669
        ///3270	1026	381	185	293	3520	1705	1610	3302	628	3420	524	3172	244	295	39
        ///4142	1835	4137	3821 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kvvfl kvvfl olud wjqsqa olud frc
        ///slhm rdfm yxb rsobyt rdfm
        ///pib wzfr xyoakcu zoapeze rtdxt rikc jyeps wdyo hawr xyoakcu hawr
        ///ismtq qwoi kzt ktgzoc gnxblp dzfayil ftfx asscba ionxi dzfayil qwoi
        ///dzuhys kfekxe nvdhdtj hzusdy xzhehgc dhtvdnj oxwlvef
        ///gxg qahl aaipx tkmckn hcsuhy jsudcmy kcefhpn kiasaj tkmckn
        ///roan kqnztj edc zpjwb
        ///yzc roc qrygby rsvts nyijgwr xnpqz
        ///jqgj hhgtw tmychia whkm vvxoq tfbzpe ska ldjmvmo
        ///nyeeg omn geyen ngyee rcjt rjuxh
        ///qpq udci tnp fdfk kffd eyzvmg ufppf wfuodj toamfn tkze jzsb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///2
        ///0
        ///0
        ///-2
        ///-2
        ///-1
        ///-4
        ///-5
        ///-6
        ///0
        ///1
        ///-5
        ///-3
        ///-10
        ///-8
        ///-2
        ///-13
        ///-14
        ///-15
        ///-8
        ///-5
        ///-13
        ///-16
        ///-21
        ///-3
        ///-14
        ///-23
        ///-9
        ///-11
        ///-19
        ///-29
        ///-2
        ///-20
        ///-28
        ///1
        ///-3
        ///-35
        ///1
        ///-20
        ///-4
        ///-37
        ///-11
        ///-27
        ///-33
        ///-43
        ///-20
        ///-5
        ///-9
        ///-22
        ///-47
        ///-5
        ///-49
        ///-13
        ///-22
        ///-2
        ///-2
        ///-51
        ///-53
        ///-22
        ///-38
        ///-16
        ///-37
        ///-30
        ///-49
        ///-48
        ///-35
        ///-5
        ///-42
        ///-21
        ///-31
        ///-61
        ///-43
        ///-31
        ///-72
        ///-35
        ///-3
        ///-31
        ///-65
        ///-78
        ///2
        ///-17
        ///-80
        ///-10
        ///-6
        ///-68
        ///-69
        ///-44
        ///-71
        ///-78
        ///-89
        ///-19
        ///-22
        ///-28
        ///-21
        ///-7
        ///-54
        ///-63
        ///-48
        ///-70
        ///-73
        ///-52
        ///-47
        ///-49
        ///-2
        ///-91
        ///-65
        ///-76
        ///-58
        ///-47
        ///-45
        ///-2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
    }
}
