//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeRunner.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 147,37,249,1,31,2,226,0,161,71,254,243,183,255,30,70.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n,ne,ne,se,se,se,se,s,se,se,sw,s,s,s,s,s,sw,sw,s,sw,sw,sw,sw,s,sw,sw,sw,nw,nw,n,nw,n,sw,sw,nw,nw,nw,nw,nw,n,s,nw,nw,nw,n,se,nw,n,s,ne,se,n,n,nw,ne,n,nw,nw,n,nw,sw,n,n,n,n,n,s,n,n,n,ne,ne,ne,ne,se,n,ne,n,n,n,n,ne,ne,sw,n,n,ne,ne,ne,ne,ne,ne,sw,ne,se,ne,ne,ne,ne,se,ne,ne,sw,ne,s,n,n,s,se,ne,se,n,se,ne,se,se,ne,ne,ne,ne,ne,ne,ne,se,ne,ne,se,se,se,ne,se,s,nw,se,ne,se,n,se,se,s,se,se,se,sw,n,se,se,se,se,se,se,n,se,s,se,sw,se,nw,se,se,se,se,se,se,se,sw,sw,s,nw,s,se,nw,se,se,s,s,se,se,s,se,nw,nw,se,s,se,se,s,s,s,s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 &lt;-&gt; 889, 1229, 1736
        ///1 &lt;-&gt; 1, 480, 793, 1361
        ///2 &lt;-&gt; 607
        ///3 &lt;-&gt; 273, 422
        ///4 &lt;-&gt; 965, 1052, 1130, 1591
        ///5 &lt;-&gt; 1998
        ///6 &lt;-&gt; 483, 1628
        ///7 &lt;-&gt; 1012, 1242, 1244, 1491
        ///8 &lt;-&gt; 524
        ///9 &lt;-&gt; 13, 281, 1498
        ///10 &lt;-&gt; 10
        ///11 &lt;-&gt; 1956
        ///12 &lt;-&gt; 598, 621, 1210
        ///13 &lt;-&gt; 9
        ///14 &lt;-&gt; 1728
        ///15 &lt;-&gt; 912, 1461
        ///16 &lt;-&gt; 1489, 1680, 1994
        ///17 &lt;-&gt; 854
        ///18 &lt;-&gt; 1157, 1299
        ///19 &lt;-&gt; 759
        ///20 &lt;-&gt; 1352, 1831
        ///21 &lt;-&gt; 1425
        ///22 &lt;-&gt; 470, 685, 857, 1526
        ///23 &lt;-&gt; 405
        ///24 &lt;-&gt; 43, 536, 1849
        ///25 &lt;-&gt; 1674
        ///26 &lt;-&gt; 26, 1738
        ///27 &lt;-&gt; 558
        ///28 &lt;-&gt; 1863
        ///29 &lt;-&gt; 154,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 3
        ///1: 2
        ///2: 6
        ///4: 4
        ///6: 4
        ///8: 8
        ///10: 9
        ///12: 8
        ///14: 5
        ///16: 6
        ///18: 8
        ///20: 6
        ///22: 12
        ///24: 6
        ///26: 12
        ///28: 8
        ///30: 8
        ///32: 10
        ///34: 12
        ///36: 12
        ///38: 8
        ///40: 12
        ///42: 12
        ///44: 14
        ///46: 12
        ///48: 14
        ///50: 12
        ///52: 12
        ///54: 12
        ///56: 10
        ///58: 14
        ///60: 14
        ///62: 14
        ///64: 14
        ///66: 17
        ///68: 14
        ///72: 14
        ///76: 14
        ///80: 14
        ///82: 14
        ///88: 18
        ///92: 14
        ///98: 18.
        /// </summary>
        internal static string Day13Input {
            get {
                return ResourceManager.GetString("Day13Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlqgujun.
        /// </summary>
        internal static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x1/14,s12,x11/9,s3,pb/f,x0/12,pd/j,x5/3,s14,x13/6,s4,x2/5,s5,x14/0,pk/c,s7,x7/15,s5,x8/0,s13,x6/7,s8,x9/4,po/j,x0/15,pb/h,x10/1,s10,x0/8,pk/l,x5/13,s5,x15/4,s8,x14/5,s11,x13/9,pi/h,x2/5,po/f,x11/3,s14,x0/9,s12,x5/2,pm/h,x14/1,s12,pc/k,x12/7,s15,x6/8,pn/h,x7/2,pk/m,s8,x12/6,pa/n,s15,x15/9,pg/h,s11,x10/2,s6,x12/5,pc/b,x3/9,s3,x4/5,s14,x11/2,s14,x10/12,pm/n,s11,x8/1,s11,x5/7,pl/e,x6/14,s15,x7/0,pb/f,x5/12,s12,x11/4,s13,x13/8,pp/i,x14/0,s4,x3/11,s12,x5/14,s6,x11/8,s3,x9/14,s2,x12/0,s12,pc/a,x13/8,pn/d,x15/9,pl/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 61697637962276641366442297247367117738114719863473648131982449728688116728695866572989524473392982963976411147683588415878214189996163533584547175794158118148724298832798898333399786561459152644144669959887341481968319172987357989785791366732849932788343772112176614723858474959919713855398876956427631354172668133549845585632211935573662181331613137869866693259374322169811683635325321597242889358147123358117774914653787371368574784376721652181792371635288376729784967526824915192526744935187989571347746222113 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1Input {
            get {
                return ResourceManager.GetString("Day1Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62	1649	1731	76	51	1295	349	719	52	1984	2015	2171	981	1809	181	1715
        ///161	99	1506	1658	84	78	533	242	1685	86	107	1548	670	960	1641	610
        ///95	2420	2404	2293	542	2107	2198	121	109	209	2759	1373	1446	905	1837	111
        ///552	186	751	527	696	164	114	530	558	307	252	200	481	142	205	479
        ///581	1344	994	1413	120	112	656	1315	1249	193	1411	1280	110	103	74	1007
        ///2536	5252	159	179	4701	1264	1400	2313	4237	161	142	4336	1061	3987	2268	4669
        ///3270	1026	381	185	293	3520	1705	1610	3302	628	3420	524	3172	244	295	39
        ///4142	1835	4137	3821 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2Input {
            get {
                return ResourceManager.GetString("Day2Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kvvfl kvvfl olud wjqsqa olud frc
        ///slhm rdfm yxb rsobyt rdfm
        ///pib wzfr xyoakcu zoapeze rtdxt rikc jyeps wdyo hawr xyoakcu hawr
        ///ismtq qwoi kzt ktgzoc gnxblp dzfayil ftfx asscba ionxi dzfayil qwoi
        ///dzuhys kfekxe nvdhdtj hzusdy xzhehgc dhtvdnj oxwlvef
        ///gxg qahl aaipx tkmckn hcsuhy jsudcmy kcefhpn kiasaj tkmckn
        ///roan kqnztj edc zpjwb
        ///yzc roc qrygby rsvts nyijgwr xnpqz
        ///jqgj hhgtw tmychia whkm vvxoq tfbzpe ska ldjmvmo
        ///nyeeg omn geyen ngyee rcjt rjuxh
        ///qpq udci tnp fdfk kffd eyzvmg ufppf wfuodj toamfn tkze jzsb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4Input {
            get {
                return ResourceManager.GetString("Day4Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///2
        ///0
        ///0
        ///-2
        ///-2
        ///-1
        ///-4
        ///-5
        ///-6
        ///0
        ///1
        ///-5
        ///-3
        ///-10
        ///-8
        ///-2
        ///-13
        ///-14
        ///-15
        ///-8
        ///-5
        ///-13
        ///-16
        ///-21
        ///-3
        ///-14
        ///-23
        ///-9
        ///-11
        ///-19
        ///-29
        ///-2
        ///-20
        ///-28
        ///1
        ///-3
        ///-35
        ///1
        ///-20
        ///-4
        ///-37
        ///-11
        ///-27
        ///-33
        ///-43
        ///-20
        ///-5
        ///-9
        ///-22
        ///-47
        ///-5
        ///-49
        ///-13
        ///-22
        ///-2
        ///-2
        ///-51
        ///-53
        ///-22
        ///-38
        ///-16
        ///-37
        ///-30
        ///-49
        ///-48
        ///-35
        ///-5
        ///-42
        ///-21
        ///-31
        ///-61
        ///-43
        ///-31
        ///-72
        ///-35
        ///-3
        ///-31
        ///-65
        ///-78
        ///2
        ///-17
        ///-80
        ///-10
        ///-6
        ///-68
        ///-69
        ///-44
        ///-71
        ///-78
        ///-89
        ///-19
        ///-22
        ///-28
        ///-21
        ///-7
        ///-54
        ///-63
        ///-48
        ///-70
        ///-73
        ///-52
        ///-47
        ///-49
        ///-2
        ///-91
        ///-65
        ///-76
        ///-58
        ///-47
        ///-45
        ///-2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5Input {
            get {
                return ResourceManager.GetString("Day5Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4	1	15	12	0	9	9	5	5	8	7	3	14	5	12	3.
        /// </summary>
        internal static string Day6Input {
            get {
                return ResourceManager.GetString("Day6Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uglvj (99) -&gt; ymfjt, gkpgf
        ///vvwrg (51)
        ///qrpgt (5)
        ///qhqbqj (55)
        ///taxdaf (23)
        ///zbbdyc (81)
        ///xhymdo (185) -&gt; errip, lsppdni, mxukll
        ///qlrcubm (81)
        ///ukgzz (7)
        ///ubvvr (288) -&gt; hrpzu, msjeeks, ozizlok
        ///zfotzg (45) -&gt; ovomgd, mqhwlq
        ///khdgj (49)
        ///idjugav (99)
        ///heuuqx (77)
        ///yierd (96) -&gt; ubnxkza, whlsvf, pnnpym, tznsg
        ///yciccp (173) -&gt; ijpsv, fjtafl, lxwntcm, saacvs
        ///jcekn (38)
        ///boxtod (126) -&gt; sxtbzfe, etdah
        ///iunue (25)
        ///iceaj (216) -&gt; zbqgiy, taxdaf
        ///vobnuq (64)
        ///grkyj (7)
        ///etgjaum (61)
        ///erjcx (47)
        ///sqcodst (19)
        ///vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7Input {
            get {
                return ResourceManager.GetString("Day7Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n dec 271 if az &lt; 3
        ///f inc -978 if nm &lt;= 9
        ///g inc -336 if ga &lt; 2
        ///egk dec 437 if y &lt; 5
        ///z dec -550 if g == -336
        ///mx dec 12 if bqr == 0
        ///mx dec 433 if ns == 0
        ///ic inc 506 if g &lt;= -327
        ///ga dec -560 if ic != 506
        ///bqr dec 570 if az &gt;= -9
        ///g dec 372 if egk != -429
        ///f dec -863 if b &gt;= -9
        ///gyc inc 844 if av &gt;= 7
        ///cr inc -781 if mx &gt;= -453
        ///ga dec 346 if cr == -781
        ///b inc -162 if z &lt; 554
        ///nno inc 504 if g &lt;= -700
        ///mx dec -32 if vkg &lt;= 6
        ///mx dec -961 if nno &lt; 509
        ///az dec 320 if ic &lt; 510
        ///nm dec 594 if ga != -354
        ///cr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8Input {
            get {
                return ResourceManager.GetString("Day8Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{&lt;&gt;},{{&lt;u!&gt;},&lt;!!!!!!!&gt;&lt;!!u!!&quot;!&gt;!!!!!&gt;!&gt;},&lt;,!!o&gt;},{}},{&lt;!&gt;},&lt;{!!a!a!!!!,!{i!!!&gt;&gt;,{&lt;!!!!i!!!&gt;&gt;}}},{{{{{&lt;&lt;{!&gt;,&lt;!&gt;,&lt;o!&gt;},&lt;!!&lt;!,i!!&lt;,!&gt;,&lt;!&gt;}e&gt;}}},{{},&lt;!!}&apos;,!&gt;},&lt;!&gt;},&lt;e,!&gt;,&lt;!!!&gt;&lt;&gt;},{}},{{{{{&lt;}i&gt;,{{}}},{&lt;!&gt;},&lt;oe!&gt;},&lt;&lt;,!!a&apos;}{&quot;!!!!!&gt;&quot;&apos;u!&gt;,&lt;!!!&gt;&apos;&gt;,{{&lt;!!u!!!!!&gt;!&gt;!!!&gt;,}&apos;u,!{!&gt;,&lt;}!&gt;},&lt;}u&gt;}}}},{&lt;{!&quot;}!&gt;!!u!&gt;},&lt;!&gt;},&lt;eoi!!}o&quot;&quot;i!!u}e&gt;},{&lt;&quot;{&gt;,{{&lt;&gt;}}}},{{&lt;{!,&gt;},{&lt;e!&apos;&quot;!,u}&gt;,{&lt;&gt;}},{{},{{&lt;!&gt;,&lt;!&lt;e!&gt;i!!!&gt;o!!!&gt;&gt;}}}},{{},{{{},{&lt;!&gt;!&gt;u&lt;&quot;&apos;o&quot;&apos;!}!&gt;,&lt;!&gt;,&lt;&quot;ea&lt;i{!!a&gt;,{&lt;a!!!!!&gt;!&gt;,&lt;a!!!&gt;&quot;ei!!&lt;iu!!!!,&gt;}}},{&lt;a!oe!!!&gt;eauu&apos;&gt;}}},{{{&lt;!u!&gt;ou!&gt;,&lt;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9Input {
            get {
                return ResourceManager.GetString("Day9Input", resourceCulture);
            }
        }
    }
}
